# Generated by Django 5.2.6 on 2025-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='center_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='list',
            name='center_lat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='center_lon',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='radius_miles',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
