# Generated by Django 5.2.6 on 2025-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_list_center_address_list_center_lat_list_center_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='style',
            field=models.TextField(default='regular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyowner',
            name='address',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
